export const SERVICE_ERROR = 'Error: The Geolocation service failed.';
export const BROWSER_ERROR = 'Error: Your browser doesn\'t support geolocation.';
export const WIDTH = 2.8;
export const HEIGHT = -187.3;
export const FOUND_LOCATION_MESSAGE = 'Your location';
export const MAP_KEY = 'AIzaSyAsPZDqrpgqq65I_XWaTkX7Y8Ac5QNLZDM';
export const WEATHER_API_KEY = '4c82d0abdf5e396e4d75d19a72f5a2e6';
export const WEATHER_API_URL = 'http://api.openweathermap.org/data/2.5/box/city?bbox=';
export const MAP_API_URL = 'https://maps.googleapis.com/maps/api/js?';
export const MIN_CIRCLE_RADIUS = 170000;
export const MAX_CIRCLE_RADIUS = 280000;
export const RADIUS_COEFFICIENT = 6000;
export const AVERAGE_RADIUS = 6;
